# .github/workflows/master-ci.yml
name: Master CI Pipeline (Inherit standard CI template)

on:
  pull_request:
  push:
    branches: ['master']
    paths-ignore: ['**/*.md']

permissions:
  contents: read

jobs:
  call-standard:
    uses: Jlong0104/spring-hello-problem/.github/workflows/standard-master-ci.yml@master
    with:
      image_name:   'spring-hello-problem'
      image_registry: 'docker.io'
      chart_path:   'charts/java-app'
      release_name: 'spring-hello-problem'
      namespace:    'spring-hello-problem'
      helm_version: '3.14.4'
      use_kind:     true
      push_image:   true
      dockerfile:   './Dockerfile'
      context:      '.'
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_token:   ${{ secrets.DOCKER_HUB_TOKEN }}
